[2023-03-12T13:17:14.980+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Dag_master.dag_1_completed_status scheduled__2023-03-12T13:16:00+00:00 [queued]>
[2023-03-12T13:17:14.993+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Dag_master.dag_1_completed_status scheduled__2023-03-12T13:16:00+00:00 [queued]>
[2023-03-12T13:17:14.993+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-12T13:17:14.993+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-12T13:17:14.993+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-12T13:17:15.014+0000] {taskinstance.py:1300} INFO - Executing <Task(ExternalTaskSensor): dag_1_completed_status> on 2023-03-12 13:16:00+00:00
[2023-03-12T13:17:15.022+0000] {standard_task_runner.py:55} INFO - Started process 91 to run task
[2023-03-12T13:17:15.025+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Dag_master', 'dag_1_completed_status', 'scheduled__2023-03-12T13:16:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/child_master_dag.py', '--cfg-path', '/tmp/tmpxj83qnf3']
[2023-03-12T13:17:15.025+0000] {standard_task_runner.py:83} INFO - Job 31: Subtask dag_1_completed_status
[2023-03-12T13:17:15.098+0000] {task_command.py:388} INFO - Running <TaskInstance: Dag_master.dag_1_completed_status scheduled__2023-03-12T13:16:00+00:00 [running]> on host 85f2bfd08863
[2023-03-12T13:17:15.183+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Dag_master
AIRFLOW_CTX_TASK_ID=dag_1_completed_status
AIRFLOW_CTX_EXECUTION_DATE=2023-03-12T13:16:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-12T13:16:00+00:00
[2023-03-12T13:19:15.334+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 215, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 120.14939212999889 seconds exceeds the specified timeout of 120.
[2023-03-12T13:19:15.340+0000] {taskinstance.py:1323} INFO - Immediate failure requested. Marking task as FAILED. dag_id=Dag_master, task_id=dag_1_completed_status, execution_date=20230312T131600, start_date=20230312T131714, end_date=20230312T131915
[2023-03-12T13:19:15.354+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 31 for task dag_1_completed_status (Sensor has timed out; run duration of 120.14939212999889 seconds exceeds the specified timeout of 120.; 91)
[2023-03-12T13:19:15.380+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-12T13:19:15.410+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
